# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rough Draft
subtitle: Chris Klanac's development notebook
# email: your-email@domain.com
description: > # this means to ignore newlines, content must be indented
  Chris Klanac's development notebook
# It appears in your document head meta (for Google search results) and in your feed.xml

# the subpath of your site, e.g. /blog
baseurl: ""

# https://jekyllrb.com/docs/permalinks/#built-in-permalink-styles
permalink: pretty

url: "http://cklanac.github.io/" # the base hostname & protocol for your site

twitter_username: cklanac
github_username:  cklanac

# Build settings
markdown: kramdown

# http://kramdown.gettalong.org/parser/gfm.html
kramdown:
  input: GFM

# Fixes "invalid date... in the YAML front matter." in Travis build
# https://github.com/jekyll/jekyll/issues/3330
exclude: [vendor]
